metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  dataset_dir: /root/autodl-tmp
  image_dir: train_3
  anno_path: coco_train_3.json

  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  dataset_dir: /root/autodl-tmp
  #image_dir: valid1
  #anno_path: coco_valid_singleclass_wh_bboxfixed_rotated1.json

  image_dir: test_rotated_3/images
  anno_path: coco_test_3.json

  allow_empty: true

TestDataset:
  name: ImageFolder
  dataset_dir: /root/autodl-tmp
  image_dir: test_rotated/images
  anno_path: test_rotated/coco_test_rotated.json

