task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ["bbox"]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 1
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/train_2
    ann_file: /root/autodl-tmp/coco_train_2.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    #img_folder: /root/autodl-tmp/valid_5
    img_folder: /root/autodl-tmp/test_rotated_2/images
    #ann_file: /root/autodl-tmp/coco_valid_5.json
    ann_file: /root/autodl-tmp/coco_test_2.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
