worker_num: 4

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {prob: 0.8}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {prob: 0.8}
    - RandomFlip: {}
  batch_transforms:
    # 固定输入尺寸为 1024x1024（不多尺度、不随机尺寸）
    - Resize: {target_size: [1024, 1024], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {retain_origin_box: true}
    - BboxXYXY2XYWH: {}
    - Permute: {}
    - PadGT: {only_origin_box: true}
  batch_size: 4
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: true


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [1024, 1024], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 4
  shuffle: false
  drop_last: false


TestReader:
  inputs_def:
    image_shape: [3, 1024, 1024]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [1024, 1024], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
